plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "app/admin/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
  TargetRubyVersion: 3.4.4

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
