# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.4'

gem 'bootsnap', '>= 1.4.4', require: false
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.4'
gem 'rails', '~> 7.2.2', '>= 7.2.2.1'

# API gems
gem 'jsonapi-serializer'
gem 'rack-cors'

# File processing
gem 'csv'
gem 'roo'

# Background jobs
gem 'redis'
gem 'sidekiq'

# Documentation
gem 'rswag'

group :development, :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end

group :development do
  gem 'brakeman'
  gem 'listen', '~> 3.3'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
end
