name: Rails CI

on:
  push:
    branches: [ "main", "improvements" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ceap_api_test
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version 
          bundler-cache: true # Cache das gems para acelerar execuções futuras

      - name: Configurar Variáveis de Ambiente
        # Variáveis que o database.yml precisa
        run: |
          echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_USER=postgres" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=password" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
          echo "RAILS_ENV=test" >> $GITHUB_ENV

      - name: Preparar o Banco de Dados de Teste
        run: |
          cd ceap-api
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Rodar o Linter (RuboCop)
        run: |
          cd ceap-api
          bundle exec rubocop

      - name: Rodar Testes de Segurança (Brakeman)
        run: |
          cd ceap-api
          bundle exec brakeman --no-pager

      - name: Rodar a suíte de testes (RSpec)
        run: |
          cd ceap-api
          bundle exec rspec